Adds CSP rules to securethenews
freedomofpress/securethenews pull request #288
Opened 2020-10-30 14:15 UTC by SaptakS

Few things to note:
- Added sha-256 for all the unsafe-inline restrictions.
- Sadly had to add unsafe-eval because build.js uses it for webpack.
- The gravatar URL in admin doesn't work, which is consistent with freedom.press (though securedrop seems to exclude CSP altogether in `/admin/` path)
- I haven't included `analytics.freedom.press` in any of the rules, neither piwik sha256 because even though I see PIWIK_ID mentioned in production.py, I don't see them in the HTML loaded for the website. Is it being used somewhere? Then I will need to add those to the rules.

Apart from that, everything should mostly be working.

2020-11-06 16:55 UTC, maeve-fpf requested changes
Implementation looks good, and I agree that `'self'` is the way to go, but multiple environment variables for adding Google Storage was overengineering it -- in the deploy, you will have `GS_CUSTOM_ENDPOINT` set to `https://media.securethe.news`, so let's add that one value to each of CSP_IMG_SRC, CSP_MEDIA_SRC, and CSP_OBJECT_SRC. No splitting necessary, and you can read it out of `os.environ` earlier in the code and use that value when initializing the lists rather than having to `.extend`.

2020-11-09 12:20 UTC, SaptakS commented on securethenews/settings/base.py
> +    GS_CUSTOM_ENDPOINT,
I am guessing this should work?

2020-11-09 18:29 UTC, maeve-fpf approved these changes

2020-11-09 18:29 UTC, maeve-fpf commented on securethenews/settings/base.py
> +    GS_CUSTOM_ENDPOINT,
Looks great!

2020-11-09 23:40 UTC, harrislapiroff approved these changes
With Maeve's approval, I think this is good to go.

2020-11-09 23:40 UTC, merged