Onion address override
freedomofpress/securethenews pull request #296
Opened 2020-12-02 22:36 UTC by chigby

This pull request slightly reorganizes the scan result data to support overriding the `onion_available` result on a per-site basis. I've done this by:

1. Renaming the `Scan.onion_available` to `Scan.onion_location_header`. This reflects that what the scan is testing for right now is the presence or absence of the header.
2. Add a `onion_address` field to the `Site` model. This is a url field that editors can fill in with the known Onion address for the site.
3. Replace the `Scan.onion_available` field with a property of the same name that checks if the scanned site has an onion address. If so, then we always return `True`, otherwise we return the `onion_location_header` result.

Fixes #283

2020-12-14 11:05 UTC, SaptakS requested changes
Apart from the comment, logically everything else looks good to me.

2020-12-14 11:05 UTC, SaptakS commented on sites/models.py
> +    )
I think we will need to add this in the panel for allowing adding/editing onion addresses

2020-12-14 21:58 UTC, chigby commented
Added a panel for `onion_address`

2020-12-15 12:01 UTC, SaptakS approved these changes
looks good to me.

2020-12-15 12:01 UTC, merged